# Generated by Django 6.0.3 on 2026-03-06 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_middlewaretestmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_dummy',
            },
        ),
    ]
